Release/1.5.1
ondewo/ondewo-t2s-client-angular pull request #2
Opened 2021-05-11 11:57 UTC by Phips0812

2021-05-11 13:19 UTC, gaborod16 requested changes
Seems like the release `1.5.0` was skipped completely :open_mouth:

2021-05-11 13:19 UTC, gaborod16 commented on RELEASE.md
> +NO RELEASE FOR 1.5.0
Now this is confusing.

So, there is no release `1.5.0` but there are Release Notes for it that then say "No release for 1.5.0".
:sweat_smile: 

The issue here is, what should be the next release.
So, if the API moved to `1.5.0` the client needs to move to `1.5.*`.
Since the `1.5.0` didn't exist, we should do that one. :smile: 

But the situation is odd, maybe I am overlooking something.

2021-05-11 13:19 UTC, gaborod16 commented on package.json
>    "description": "Ondewo natural language understanding client library for angular",
The description in the `package.json` :eyes:

2021-05-11 13:19 UTC, gaborod16 commented on package.json
> +  "version": "1.5.1",
Exactly, so, it is odd to move from `1.4.0` to `1.5.1` jumping over `1.5.0`.

2021-05-11 13:19 UTC, gaborod16 commented on src/package.json
> +    "publish-npm": "npm publish ../npm --access public"
oh, nice!

2021-05-12 08:10 UTC, closed without merging

2021-05-12 08:11 UTC, Phips0812 commented
Release 1.5.0 instead of this to not jump over the version.